name=MT6826S SPI
version=1.0.0
author=BrozuTechWorks
maintainer=Bruno Cerna <brunocc24@gmail.com>
sentence=Arduino SPI library for MagnTek’s magnetic angle encoder MT6826S.
paragraph=Read 15-bit angle via SPI from MT6826S, configure ABZ, UVW, PWM outputs and program EEPROM
category=Sensors
url=https://github.com/mynameisbrozu/MT6826S-SPI
architectures=*
includes=MT6826S_SPI.h
